&ref_api_key
project_identifier: jceeditor
api_key: 
base_path: 
preserve_hierarchy: true
files:
  - source: /language/en-GB/en-GB.com_jce.ini
    translation: language/%locale%/%original_file_name%
    type: ini
  - source: /language/en-GB/en-GB.com_jce_pro.ini
    translation: language/%locale%/%original_file_name%
    type: ini
  - source: /language/en-GB/en-GB.pkg_jce_manifest.ini
    translation: /language/%locale%/%original_file_name%
    type: ini
  - source: /administrator/language/en-GB/en-GB.com_jce*.ini
    translation: administrator/language/%locale%/%original_file_name%
    type: ini
  - source: /administrator/language/en-GB/en-GB.pkg_jce*.ini
    translation: administrator/language/%locale%/%original_file_name%
    type: ini
  - source: /administrator/language/en-GB/en-GB.plg_fields_mediajce*.ini
    translation: administrator/language/%locale%/%original_file_name%
    type: ini
  - source: /administrator/language/en-GB/en-GB.plg_content_jce*.ini
    translation: administrator/language/%locale%/%original_file_name%
    type: ini
  - source: /administrator/language/en-GB/en-GB.plg_editors_jce*.ini
    translation: administrator/language/%locale%/%original_file_name%
    type: ini
  - source: /administrator/language/en-GB/en-GB.plg_extension_jce*.ini
    translation: administrator/language/%locale%/%original_file_name%
    type: ini
  - source: /administrator/language/en-GB/en-GB.plg_installer_jce*.ini
    translation: administrator/language/%locale%/%original_file_name%
    type: ini
  - source: /administrator/language/en-GB/en-GB.plg_quickicon_jce*.ini
    translation: administrator/language/%locale%/%original_file_name%
    type: ini
  - source: /administrator/language/en-GB/en-GB.plg_system_jce*.ini
    translation: administrator/language/%locale%/%original_file_name%
    type: ini
